name: Release npm package

on:
  push:
    branches:
      - some-branch # Your release branch

jobs:
  notify_start:
    if: ${{ secrets.TELEGRAM_CHAT_ID && secrets.TELEGRAM_BOT_TOKEN }}
    name: Notify about start releasing
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Creating release for ${{ github.repository }}...

  build:
    runs-on: ubuntu-18.04
    outputs:
      published: ${{ steps.release.outputs.new-release-published }}
      version: ${{ steps.release.outputs.release-version }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          pnpm i --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: |
          pnpm run test
        env:
          VITE_INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

      - name: Build artifacts
        run: |
          pnpm run build

      - name: Semantic release
        id: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify_end:
    if: ${{ secrets.TELEGRAM_CHAT_ID && secrets.TELEGRAM_BOT_TOKEN }}
    name: Notify about finish releasing
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Notification about publishing
        if: ${{ needs.build.outputs.published }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✨ Release for ${{ github.repository }}@${{ needs.build.outputs.version }} has been created!

      - name: Notification about skipping
        if: ${{ !needs.build.outputs.published }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🌚 Ended without a new release for ${{ github.repository }}
